# Puerto del servidor (por defecto es 8080)
server.port=8080

# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/eventos_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Configuración de JPA/Hibernate
# 'none' porque ya creamos la tabla manualmente con SQL. 
# Si prefieres que Spring la cree/modifique sola, cambia 'none' por 'update'
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true